# 1. Base image
FROM node:20-alpine AS base
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

# 2. Builder stage
FROM base AS builder
WORKDIR /app
ARG NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
COPY . .
RUN yarn build

# 3. Production stage
FROM node:20-alpine AS production
WORKDIR /app
ENV NODE_ENV=production

# Standalone mode handles dependencies, so we just copy the final build
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

EXPOSE 3000
# Run the server.js file generated by Next.js standalone mode
CMD ["node", "server.js"]